---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "prod-us-east1-100k-object-write-config-dvfx"
  namespace: "default"
  labels:
    app: "prod-us-east1-100k-object-write"
data:
  UNIVERSE: "prod"
  SCENARIO: "100k-object-write"
  REGION: "us-east1"
  OPERATION: "ResumableWriteObject"
  WRITE_LENGTH: "100000"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "prod-us-east1-100k-object-write"
  namespace: "default"
  labels:
    app: "prod-us-east1-100k-object-write"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "prod-us-east1-100k-object-write"
  template:
    metadata:
      labels:
        app: "prod-us-east1-100k-object-write"
    spec:
      hostNetwork: true
      containers:
      - name: "gcs-perf-prober"
        image: "us-central1-docker.pkg.dev/gcs-grpc-team-testing/my-repository/gcs-perf-prober:latest"
        #image: "us-central1-docker.pkg.dev/gcs-grpc-team-testing/my-repository/perf-gauge@sha256:811dbba5860dfe58330be0154d85a7c57a905396724c5ae537f0f224f7151858"
        env:
        - name: "UNIVERSE"
          valueFrom:
            configMapKeyRef:
              key: "UNIVERSE"
              name: "prod-us-east1-100k-object-write-config-dvfx"
        - name: "SCENARIO"
          valueFrom:
            configMapKeyRef:
              key: "SCENARIO"
              name: "prod-us-east1-100k-object-write-config-dvfx"
        - name: "REGION"
          valueFrom:
            configMapKeyRef:
              key: "REGION"
              name: "prod-us-east1-100k-object-write-config-dvfx"
        - name: "OPERATION"
          valueFrom:
            configMapKeyRef:
              key: "OPERATION"
              name: "prod-us-east1-100k-object-write-config-dvfx"
        - name: "WRITE_LENGTH"
          valueFrom:
            configMapKeyRef:
              key: "WRITE_LENGTH"
              name: "prod-us-east1-100k-object-write-config-dvfx"